# Generated by Django 4.1.2 on 2022-10-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_item_alter_pedido_itens'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tamanho',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
